CREATE OR REPLACE TRIGGER trg_check_age
  BEFORE INSERT OR UPDATE
  ON Kunde
  FOR EACH 
BEGIN
  IF(MONTHS_BETWEEN(CURRENT_DATE,:new.geburtsdatum) < 216)) THEN
    RAISE_APPLICATION_ERROR(-20000, 'too young');
  END IF;
END;